version: '3.1'
services:
    postgres:
        image: postgres:12
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
    vcs:
        build: VCS/
        ports:
            - "80:80"
        depends_on: 
            - "postgres"
    ml:
        build: ML/
        ports:
            - "8000:80"
        depends_on:
            - "vcs"